#!/bin/bash
set -euo pipefail

DOMAIN="the-exp.net"
SERVER_IP="${1:?Usage: $0 <server-ip> [dns-provider]}"
DNS_PROVIDER="${2:-cloudflare}"

echo "=== DNS Configuration for $DOMAIN ==="
echo "Server IP: $SERVER_IP"
echo "DNS Provider: $DNS_PROVIDER"
echo ""

echo "Required DNS Records:"
echo "=========================================="
echo ""
echo "1. A Record (Root domain → Server IP)"
echo "   Type: A"
echo "   Name: @"
echo "   Value: $SERVER_IP"
echo "   TTL: 3600"
echo ""
echo "2. CNAME Record (WWW → Root domain)"
echo "   Type: CNAME"
echo "   Name: www"
echo "   Value: $DOMAIN"
echo "   TTL: 3600"
echo ""
echo "3. CNAME Record (Resend domain verification - get value from Resend dashboard)"
echo "   Type: CNAME"
echo "   Name: resend._domainkey"
echo "   Value: <provided-by-resend>"
echo "   TTL: 3600"
echo ""
echo "4. MX Records (Email via Resend)"
echo "   Type: MX"
echo "   Name: @"
echo "   Value: mx1.resend.com"
echo "   Priority: 10"
echo ""
echo "   Type: MX"
echo "   Name: @"
echo "   Value: mx2.resend.com"
echo "   Priority: 20"
echo ""
echo "5. SPF Record (Email sender authorization)"
echo "   Type: TXT"
echo "   Name: @"
echo "   Value: v=spf1 include:resend.com ~all"
echo ""
echo "6. DKIM Record (Email signing via Resend - get value from Resend dashboard)"
echo "   Type: TXT"
echo "   Name: resend._domainkey"
echo "   Value: <provided-by-resend>"
echo ""
echo "7. DMARC Record (Email policy)"
echo "   Type: TXT"
echo "   Name: _dmarc"
echo "   Value: v=DMARC1; p=none; rua=mailto:dmarc@$DOMAIN; ruf=mailto:dmarc@$DOMAIN"
echo ""
echo "8. TXT Record (Resend domain verification)"
echo "   Type: TXT"
echo "   Name: <provided-by-resend>"
echo "   Value: <provided-by-resend>"
echo ""

if [ "$DNS_PROVIDER" = "cloudflare" ]; then
    echo "=== Cloudflare Setup Instructions ==="
    echo ""
    echo "1. Go to https://dash.cloudflare.com and add $DOMAIN"
    echo "2. At your domain registrar, change nameservers to Cloudflare's assigned NS"
    echo "3. Wait for DNS propagation (up to 48h, usually <1h)"
    echo "4. In Cloudflare DNS settings, add all records above"
    echo "5. Enable Cloudflare proxy (orange cloud) for A and CNAME records"
    echo "6. Set SSL/TLS mode to 'Full (Strict)'"
    echo "7. Enable 'Always Use HTTPS' in SSL/TLS settings"
    echo "8. Enable 'Automatic HTTPS Rewrites'"
    echo ""
    echo "When using Cloudflare proxy, SSL is handled by Cloudflare."
    echo "You can still use Let's Encrypt as backup via certbot."
elif [ "$DNS_PROVIDER" = "manual" ]; then
    echo "=== Manual DNS Setup ==="
    echo ""
    echo "Add all the DNS records above at your domain registrar's DNS management panel."
    echo "Most registrars propagate changes within 1-4 hours."
    echo ""
    echo "After configuring DNS, verify with:"
    echo "  dig $DOMAIN A +short"
    echo "  dig www.$DOMAIN CNAME +short"
    echo "  dig $DOMAIN MX +short"
    echo "  dig $DOMAIN TXT +short"
    echo "  dig _dmarc.$DOMAIN TXT +short"
fi

echo ""
echo "=== DNS Propagation Check ==="
echo ""
echo "After configuring DNS records, run:"
echo "  ./scripts/verify-dns.sh $DOMAIN"