#!/bin/bash
set -euo pipefail

DOMAIN="the-exp.net"
EMAIL="${1:?Usage: $0 <email>}"

echo "=== Resend Domain Verification Setup ==="
echo ""
echo "This script guides you through configuring Resend for $DOMAIN"
echo ""
echo "Prerequisites:"
echo "  - Resend account created at https://resend.com"
echo "  - Resend API key available"
echo ""

echo "[Step 1] Add domain in Resend Dashboard"
echo "  1. Go to https://resend.com/domains"
echo "  2. Click 'Add Domain'"
echo "  3. Enter: $DOMAIN"
echo "  4. Select 'Send from domain' (not subdomain)"
echo "  5. Click 'Add'"
echo ""

echo "[Step 2] Add DNS records shown by Resend"
echo "  Resend will show you specific DNS records to add."
echo "  These typically include:"
echo ""
echo "  a) SPF TXT Record:"
echo "     Type: TXT"
echo "     Name: @"
echo "     Value: v=spf1 include:resend.com ~all"
echo ""
echo "  b) DKIM CNAME Record:"
echo "     Type: CNAME"
echo "     Name: resend._domainkey"
echo "     Value: <value-shown-by-resend>"
echo ""
echo "  c) Domain verification TXT Record:"
echo "     Type: TXT"
echo "     Name: <value-shown-by-resend>"
echo "     Value: <value-shown-by-resend>"
echo ""
echo "  d) MX Records (for receiving replies):"
echo "     Type: MX, Name: @, Value: mx1.resend.com, Priority: 10"
echo "     Type: MX, Name: @, Value: mx2.resend.com, Priority: 20"
echo ""

echo "[Step 3] Add DMARC Record"
echo "  Type: TXT"
echo "  Name: _dmarc"
echo "  Value: v=DMARC1; p=none; rua=mailto:dmarc@$DOMAIN; ruf=mailto:dmarc@$DOMAIN"
echo ""

echo "[Step 4] Wait for DNS propagation"
echo "  DNS changes can take up to 48 hours to propagate."
echo "  You can check propagation at: https://mxtoolbox.com/DNSLookup.aspx"
echo ""

echo "[Step 5] Verify domain in Resend"
echo "  1. Go back to https://resend.com/domains"
echo "  2. Click 'Verify' on your domain"
echo "  3. If DNS is propagated, it should show as verified"
echo ""

echo "[Step 6] Add Resend configuration to .env"
echo "  Add these environment variables:"
echo ""
echo "  RESEND_API_KEY=re_xxxxxxxxxxxx"
echo "  RESEND_FROM_EMAIL=hello@$DOMAIN"
echo ""

echo "=== Verification Commands ==="
echo "  Check SPF:   dig $DOMAIN TXT +short | grep spf"
echo "  Check DKIM:  dig resend._domainkey.$DOMAIN CNAME +short"  
echo "  Check DMARC: dig _dmarc.$DOMAIN TXT +short"
echo "  Check MX:    dig $DOMAIN MX +short"
echo ""
echo "  Automated check: ./scripts/verify-dns.sh $DOMAIN"